version: '3'

services:  
  db:
    image: postgres:9.3
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - ./docker-flask/.env

  web:
    build: ./docker-flask
    volumes:
      - ./docker-flask:/src/
    env_file:
      - ./docker-flask/.env
    expose:
      - 8080
    command: gunicorn -w 2 -b :8080 run:app
    depends_on:
      - db

  nginx:
    image: nginx:1.13.5
    ports:
      - 8080:80
    volumes:
      - ./docker-flask/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  dbdata: